### ISSUE TITLE
Suggestion for further speed improvement

### ISSUE THREAD

**Issue by BAILOOL** [fjank/sdc#1]
Great work with ANMS implementation!

There is a recent [paper](https://www.researchgate.net/publication/323388062_Efficient_adaptive_non-maximal_suppression_algorithms_for_homogeneous_spatial_keypoint_distribution) that tackles the problem of homogeneous keypoint distribution on the image. C++, Python, and Matlab interfaces are provided in this [repository](https://github.com/BAILOOL/ANMS-Codes).

**Comment by fjank** [comment]
Looks interesting, would be nice to have these algorithms in a java library, although a bit too restricted with GPL licence. As this code is MIT licenced I cannot use you code in my library. I would love to convert your code in your repository to Java, so it can be used by even more developers, but again, I think the licence is a bit too restrictive. 
If you would consider changing the licence to MIT or LGPL so it can be used freely, also in closed source commercial projects I will be happy to contribute.

**Comment by BAILOOL** [comment]
@fjank The original purpose of the paper and a code is to make it easy to use for developers and researchers without any restrictions. Indeed, I didn't know that original license had the restrictions you mentioned. I have changed to license to MIT. Feel free to use it for any purpose you want.

**Comment by fjank** [comment]
I will have a closer look at the paper/code, and will probably create a new repo for different java implementations for ANMS.
